name: 'Deploy Frontend'

inputs:
  app:
    description: 'App that we want to deploy'
    required: true
  appJson:
    description: 'App that we want to deploy in JSON formate with any additional data'
    required: false

runs:
  using: 'composite'

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: echo state value
      shell: bash
      run: echo ${{ inputs.app }}

    - name: Path
      shell: bash
      run: |
        affectedProjects=$(echo '/lib/test/hi')
        echo "affected-projects=$affectedProjects" >> $GITHUB_ENV

    - name: echo
      shell: bash
      run: echo $PRO_NAME
      env:
        PRO_NAME: ${{ format('dist/{0}', env.affected-projects) }}
