name: Build without cache

on:
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # - name: echo some string
      #   id: affected-projects
      #   shell: bash
      #   run: echo "::set-output name=projects::$(echo "My some, long stirng here, it goes")"

      - name: Login to DockerHub
        # if: ${{ contains(steps.affected-projects.outputs.projects, 'long string here') }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # if: ${{ contains(steps.affected-projects.outputs.projects, 'long string here') }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
