name: Build with cache

on:
  pull_request:
    branches: [main]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        id: docker-cache
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: docker-cache-${{ hashFiles('package-lock.json') }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        # env:
        #   cache-type: ${{ steps.docker-cache.outputs.cache-hit == 'true' && 'cache-from' || 'cache-to' }}
        #   location-type: ${{ steps.docker-cache.outputs.cache-hit == 'true' && 'src' || 'dest' }}
        with:
          context: .
          push: false
          tags: srinivas1999/cache-test:latest
          # ${{ env.cache-type }}: type=local,${{ env.location-type }}=/tmp/.buildx-cache

