name: Merge

on:
  pull_request:
    branches: [main]
    types:
      - closed

concurrency:
  group: ci-merge-${{ github.ref }}-1
  cancel-in-progress: true

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      affected-projects: ${{ steps.preparation.outputs.affected-projects }}

    steps:
      - name: Checkout PR
        uses: actions/checkout@v3

      - name: github Sha
        shell: bash
        run: echo $GITHUB_REF
        env:
          GITHUB_PR_SHA: ${{ github.event.pull_request.head.sha }}

      - name: Preparation
        id: preparation
        uses: ./.github/actions/preparation
        with:
          projects: |
            {
              "frontendProjects": [{ "projectName": "edgetag-app-ui" },
                                    { "projectName": "edgetag-website" }, 
                                    { "projectName": "edgetag-sdk-demo" }],
              "backendProjects": [{ "projectName": "crm-app-api" }, 
                                  { "projectName": "edgetag-app-api" }],
              "dockerProjects": [{ "projectName": "cloud-app-ui" }],
              "storybookProjects": [{ "projectName": "ui-kit", "buildCommand": "build-storybook", "configuration": "ci" }]
            }
